### ISSUE TITLE
the challenge now is to build the application

### ISSUE THREAD

**Issue by viniazvd** [char0n/swagger-ui-dist-vite#1]
![image](https://github.com/char0n/swagger-ui-dist-vite/assets/14836763/73770f3e-fd98-4f25-bbf1-0c72f4f779e2)

**Comment by char0n** [comment]
Yes, I can confirm. This looks like a Vite config issue again. Investigating.

**Comment by char0n** [comment]
Like I said above, it's a Vite.js config issue: https://vitejs.dev/guide/dep-pre-bundling.html#monorepos-and-linked-dependencies

I've addressed it in this repo as well by utilizing latest version of SwaggerUI@5 + Vite@4.4.9 - https://github.com/char0n/swagger-ui-dist-vite/pull/2.
